environment:
  CYG_ROOT: C:\cygwin
  CYG_MIRROR: http://cygwin.mirror.constant.com
  CYG_CACHE: C:\cygwin\var\cache\setup
  CYG_BASH: C:\cygwin\bin\bash
  BINTRAYAPIKEY:
    secure: uknPzww818XWJiLecwur9p1MfrkACOyx9d3iNrw/TuD89EoPSc8zLqKdPZjWdcQd
  matrix:
    - FLAVOR: squeak.cog.spur
    - FLAVOR: squeak.cog.v3
    - FLAVOR: squeak.stack.spur
    - FLAVOR: squeak.stack.v3
    - FLAVOR: newspeak.cog.spur
    - FLAVOR: newspeak.stack.spur

matrix:
  fast_finish: false

platform:
  - x86

clone_depth: 5

install:
  - ps: 'Start-FileDownload "http://cygwin.com/setup-x86.exe" -FileName "setup-x86.exe"'
  - 'setup-x86.exe -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P mingw64-i686-gcc-core,mingw64-i686-gcc-g++,mingw64-i686-headers,mingw64-i686-runtime,zip'

build: false

# Cygwin build script
#
# NOTES:
#
# The stdin/stdout file descriptor appears not to be valid for the Appveyor
# build which causes failures as certain functions attempt to redirect
# default file handles. Ensure a dummy file descriptor is opened with 'exec'.
test_script:
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; exec ./.travis_build.sh"'
on_success:
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; exec ./.travis_deploy.sh"'
